"""Add code_entity model and relationships

Revision ID: 785aff281cd9
Revises: 5d9000faa405
Create Date: 2026-07-14 09:57:56.174686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '785aff281cd9'
down_revision: Union[str, None] = '5d9000faa405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_entity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fully_qualified_name', sa.String(length=1024), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['code_entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_entity_file_id'), 'code_entity', ['file_id'], unique=False)
    op.create_index(op.f('ix_code_entity_id'), 'code_entity', ['id'], unique=False)
    op.create_index(op.f('ix_code_entity_parent_id'), 'code_entity', ['parent_id'], unique=False)
    op.create_index(op.f('ix_code_entity_repository_id'), 'code_entity', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_entity_repository_id'), table_name='code_entity')
    op.drop_index(op.f('ix_code_entity_parent_id'), table_name='code_entity')
    op.drop_index(op.f('ix_code_entity_id'), table_name='code_entity')
    op.drop_index(op.f('ix_code_entity_file_id'), table_name='code_entity')
    op.drop_table('code_entity')
    # ### end Alembic commands ###
